<?php
/**
 * @var Klevu\Addtocart\Block\Index $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php if ($block->isAddtocartEnabled()): ?>
    <?php
    $scriptString = <<<script

    function klevu_addtocart(id, url, qty) {
        var el = document.createElement("a");
        el.setAttribute(
            "data-post",
            '{' +
            '"action": "{$block->escapeUrl($block->getUrl('checkout/cart/add'))}",' +
            '"data": {"product":"' + id + '", "qty":"' + qty + '"}' +
            '}'
        );
        el.style.width = "0px !important";
        el.style.height = "0px !important";
        document.body.appendChild(el);
        el.click();
        document.body.removeChild(el);
    }

script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag(
        'script',
        ['type' => 'text/javascript'],
        $scriptString,
        false
    ) ?>
<?php endif; ?>
